version: '3.7'
services:
    mongodb:
        container_name: mongodb
        image: mongo
        networks: 
            - network
    backend:
        container_name: backend
        build:
            context: ./backend
        ports:
            - "3003:3003"
        networks: 
            - network
        volumes: 
            - ./backend:/usr/src/app
        depends_on:
            - "mongodb"
    frontend:
        container_name: frontend
        build:
            context: ./frontend-reducer
        ports:
            - "3000:3000"
        networks: 
            - network
        volumes: 
            - ./frontend-reducer:/usr/src/app
        depends_on:
            - "backend"
networks: 
    network:
        driver: bridge